import {
  FaMobile,
  FaKeyboard,
  FaLaptop,
  FaCamera,
  FaTv,
  FaHome,
  FaRunning,
  FaCar,
  FaGamepad,
  FaTshirt,
  FaShoePrints,
  FaChild,
  FaGuitar,
  FaBook,
  FaBaby,
  FaPaw,
  FaUtensils,
  FaBath,
  FaPlane,
  FaTree,
  FaDumbbell,
  FaGlassWhiskey,
  FaGift,
  FaHeadphones,
  FaTabletAlt,
  FaDesktop,
  FaMousePointer,
} from "react-icons/fa";

export const Categorias = [
  {
    icon: <FaMobile className="text-blue-500" />,
    label: "Smartphones",
    path: "/buscar",
    categoryValue: "TELEFONOS",
  },
  {
    icon: <FaKeyboard className="text-purple-500" />,
    label: "Periféricos",
    path: "/buscar",
    categoryValue: "PERIFÉRICOS",
  },
  {
    icon: <FaLaptop className="text-indigo-500" />,
    label: "Laptops",
    path: "/buscar",
    categoryValue: "LAPTOPS",
  },
  {
    icon: <FaCamera className="text-yellow-500" />,
    label: "Cámaras",
    path: "/buscar",
    categoryValue: "CÁMARAS",
  },
  {
    icon: <FaTv className="text-red-500" />,
    label: "Televisores",
    path: "/buscar",
    categoryValue: "TELEVISORES",
  },
  {
    icon: <FaHome className="text-green-500" />,
    label: "Hogar",
    path: "/buscar",
    categoryValue: "HOGAR",
  },
  {
    icon: <FaRunning className="text-orange-500" />,
    label: "Deportes",
    path: "/buscar",
    categoryValue: "DEPORTES",
  },
  {
    icon: <FaCar className="text-gray-600" />,
    label: "Vehículos",
    path: "/buscar",
    categoryValue: "VEHÍCULOS",
  },
  {
    icon: <FaGamepad className="text-pink-500" />,
    label: "Videojuegos",
    path: "/buscar",
    categoryValue: "GAMING",
  },
  {
    icon: <FaTshirt className="text-teal-500" />,
    label: "Ropa",
    path: "/buscar",
    categoryValue: "ROPA",
  },
  {
    icon: <FaShoePrints className="text-brown-500" />,
    label: "Zapatos",
    path: "/buscar",
    categoryValue: "ZAPATOS",
  },
  {
    icon: <FaChild className="text-amber-500" />,
    label: "Juguetes",
    path: "/buscar",
    categoryValue: "JUGUETES",
  },
  {
    icon: <FaGuitar className="text-lime-500" />,
    label: "Instrumentos",
    path: "/buscar",
    categoryValue: "INSTRUMENTOS",
  },
  {
    icon: <FaBook className="text-blue-600" />,
    label: "Libros",
    path: "/buscar",
    categoryValue: "LIBROS",
  },
  {
    icon: <FaBaby className="text-pink-300" />,
    label: "Bebés",
    path: "/buscar",
    categoryValue: "BEBÉS",
  },
  {
    icon: <FaPaw className="text-yellow-600" />,
    label: "Mascotas",
    path: "/buscar",
    categoryValue: "MASCOTAS",
  },
  {
    icon: <FaUtensils className="text-red-400" />,
    label: "Cocina",
    path: "/buscar",
    categoryValue: "COCINA",
  },
  {
    icon: <FaBath className="text-blue-300" />,
    label: "Baño",
    path: "/buscar",
    categoryValue: "BAÑO",
  },
  {
    icon: <FaPlane className="text-indigo-300" />,
    label: "Viajes",
    path: "/buscar",
    categoryValue: "VIAJE",
  },
  {
    icon: <FaTree className="text-green-600" />,
    label: "Jardín",
    path: "/buscar",
    categoryValue: "JARDÍN",
  },
  {
    icon: <FaDumbbell className="text-gray-700" />,
    label: "Fitness",
    path: "/buscar",
    categoryValue: "FITNESS",
  },
  {
    icon: <FaGlassWhiskey className="text-amber-600" />,
    label: "Bebidas",
    path: "/buscar",
    categoryValue: "BEBIDAS",
  },
  {
    icon: <FaGift className="text-pink-500" />,
    label: "Regalos",
    path: "/buscar",
    categoryValue: "REGALOS",
  },
  {
    icon: <FaHeadphones className="text-blue-400" />,
    label: "Audio",
    path: "/buscar",
    categoryValue: "AUDIO",
  },
  {
    icon: <FaTabletAlt className="text-indigo-400" />,
    label: "Tablets",
    path: "/buscar",
    categoryValue: "TABLETS",
  },
  {
    icon: <FaDesktop className="text-gray-800" />,
    label: "Computadoras",
    path: "/buscar",
    categoryValue: "COMPUTADORAS",
  },
  {
    icon: <FaKeyboard className="text-purple-400" />,
    label: "Teclados",
    path: "/buscar",
    categoryValue: "TECLADOS",
  },
  {
    icon: <FaMousePointer className="text-gray-500" />,
    label: "Mouses",
    path: "/buscar",
    categoryValue: "MOUSES",
  },
];
export default Categorias;
